CREATE TABLE `mydb`.news(
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    author TEXT NOT NULL,
    body TEXT NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);